config/routes.rb
Rails.application.routes.draw do
  root 'games#index'

  get 'games/:id' => 'games#show', as: :game
  post 'games' => 'games#create', as: :games

  post 'games/:id/player_hit' => 'games#player_hit', as: :player_hit_game
  post 'games/:id/dealer_hit' => 'games#dealer_hit', as: :dealer_hit_game

  patch 'games/:id' => 'games#end_player_turn', as: :end_player_turn

end

app/models/card.rb
class Card < ActiveRecord::Base

  belongs_to :game
  belongs_to :hand
end

app/models/game.rb
class Game < ActiveRecord::Base
  has_many :hands
  has_many :cards

  def game_outcome
    if 21 < dealer_hand.total
      "Dealer Busts! Player Wins!"
    elsif player_hand.total > dealer_hand.total
      "Player Wins!"
    else
      "Dealer Wins!"
    end
  end

  def dealer_turn
    #if dealer has blackjack, dealer automatically wins(hard mode)
    if @game.player_hand.is_finished
      if dealer_hand.total <= 16
        # dealer hits
        redirect_to dealer_hit_game_path(id: @game.id)
      else
        #dealer stays
      end
    end

  end


  def build_cards
    card_order = (1..52).to_a.shuffle

    suits = %w(H C D S)
    suits.each do |suit|
      (2..10).each do |val|
        cards.create suit: suit, value: val, name: val, position: card_order.shift
      end
      ["J", "Q", "K"].each do |val|
        cards.create suit: suit, value: 10, name: val, position: card_order.shift
      end
      cards.create suit: suit, value: 11, name: "A", position: card_order.shift
    end
  end

  def deck
    #Undealt cards
    cards.where(hand_id: nil).order("position")
  end

  def player_hand
    hands.find_by player: true
  end

  def dealer_hand
    hands.find_by player: false
  end
end

app/models/hand.rb
class Hand < ActiveRecord::Base
  belongs_to :game
  has_many :cards

  def total
    cards.pluck(:value).sum        
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  def index
  end

  def show
    @game = Game.find params[:id]
    #if player_hand.is_finished   && !dealer_hand is finished ? _dealer_response(game)
    if @game.player_hand.is_finished && !@game.dealer_hand.is_finished
      _dealer_response(@game)
    end

    #if dealer_hand.is_finished ... game.evaluate_score_to_determine_winner # ->returns  "«winner»"

  end

  def create
    @game = Game.create
    @game.build_cards
    player_hand = Hand.create game_id: @game.id, player: true
    dealer_hand = Hand.create game_id: @game.id, player: false

    2.times do
      @game.player_hand.cards << @game.deck.first
      @game.dealer_hand.cards << @game.deck.second
    end

    redirect_to game_path(id: @game.id)
  end

  def player_hit
    @game = Game.find params[:id]
    @game.player_hand.cards << @game.deck.first

    redirect_to game_path(id: @game.id)
  end

  def _dealer_response(g)
    if g.dealer_hand.total <= 16
      # dealer hits
      g.dealer_hand.cards << g.deck.first
    else
      #dealer stays
      g.dealer_hand.update_attributes(is_finished: true)
    end

    g.save

    redirect_to game_path(id: g.id)

  end

  def end_player_turn

    #query for the game from database w/ Game.find_by
    @game = Game.find params[:id]
    @game.player_hand.update_attributes(is_finished: true)

    @game.save
    redirect_to game_path(id: @game.id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/index.html.erb
<h1>Blackjack on Rails</h1>


<%= link_to 'Play', games_path, method: :post, class: "btn btn-info" %>

app/views/games/show.html.erb
<div class="well">

  <!-- display outcome -->
  <% if (@game.player_hand.is_finished) &&  (@game.dealer_hand.is_finished) %>

    <h3><%= @game.game_outcome %><h3>
      <%= link_to 'Play Again?', games_path, method: :post, class: "btn btn-success" %>
  <% end %>
</div>

<h2>Dealer Hand</h2>

<div class="row">
  <% if @game.player_hand.is_finished %>
    <% @game.dealer_hand.cards.each do |card| %>
      <%= image_tag "#{card.name}#{card.suit}.png" %>
    <% end %>
  <% else %>
    <!-- Show one card face down, the other face up -->
    <!-- <%= image_tag "card-back.png", width: "220px" %> -->
    <% @game.dealer_hand.cards.each do |card| %>
      <%= image_tag "#{card.name}#{card.suit}.png" %>
    <% end %>
  <% end %>
</div>

<h2>Player Hand</h2>

<div class="row">
  <% @game.player_hand.cards.each do |card| %>
    <%= image_tag "#{card.name}#{card.suit}.png" %>
  <% end %>
</div>
<div class="thumbnail col-md-2">
  <%= link_to "Hit", player_hit_game_path(id: @game.id), method: :post, class: "btn btn-success btn-lrg btn-block" %>
  <br/>
  <span>
    Player Total: <%= @game.player_hand.total %><br/>
  </span>
  <br/>
  <%= link_to "Stay", end_player_turn_path(id: @game.id), method: :patch, class: "btn btn-danger btn-lrg btn-block" %>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blackjack</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  
  <%= yield %>

</div>

</body>
</html>